language: python

services:
   - docker


before_install:
   - apt-get update -qq
   - apt-get upgrade -qq
   - apt-get install -qq python3 python3-pip build-essential


install:
   - pip3 install --upgrade pip
   - pip3 install -r requirements.txt
   - pip3 install mock nose


script:
   - python app/test/

