language: python

services:
   - docker


before_install:
   - sudo apt-get update
   - sudo apt-get install python3 python3-pip build-essential


install:
   - pip3 install --upgrade pip
   - pip3 install -r requirements.txt
   - pip3 install mock nose


script:
   - python app/test/

after_success:
   - set -e
   - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
   - REPO=jackofsum/ors_wsgi
   - AUTO_DEPLOY=false;
   - if [ "${TRAVIS_TAG?}" ]; then
         docker build -f Dockerfile -t $REPO:$TRAVIS_TAG .;
         docker push $REPO:$TRAVIS_TAG;
         echo "Pushed to" $REPO:$TRAVIS_TAG;
         fi
