version: '3'
services:


   # nginx reverse proxy contains ssl certs
   nginx:
      build: src/nginx/.
      ports:
      - "443:443"
      links:
         - wsgi

   wsgi:
      build: src/server/.
      environment:
      - NEO_USER=neo4j 
      - NEO_PASSWORD=localtest
      - NEO_URL=neo-cache
      - REDIS_URL=redis://redis-cache:6379
      links:
      - neo-cache
      - redis-cache

   # add bagit service

   worker:
      build: src/server/.
      environment:
      - NEO_USER=neo4j 
      - NEO_PASSWORD=localtest
      - NEO_URL=neo-cache
      - REDIS_URL=redis://redis-cache:6379
      links:
      - neo-cache
      - redis-cache
      entrypoint:
         - celery
         - -A
         - cel  
         - worker
         - --loglevel
         - info


   # expose for celery testing 
   redis-cache:
      image: redis
      #ports:
      #- '6379:6379'

   neo-cache:
      image: neo4j
      ports:
      - "7687:7687"
      - "7474:7474"
      environment:
         - NEO4J_AUTH=neo4j/localtest
